#Dashboard header carrying the title of the dashboard

  header<-dashboardHeader(title = "Evaluation Results") #dashboardHeader 

#Sidebar content of the dashboard
    sidebar<-dashboardSidebar(
      sidebarMenu(
      
        menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
        
        menuItem("Comments", tabName = "comments", icon = icon("comments")),
      
        menuItem("Visit-us", icon = icon("send",lib='glyphicon'), 
               href = "https://moodle8.camhx.ca/moodle/"),
        
        menuItem("Source Code", icon = icon("github"), 
                 href = "https://github.com/AhmadMobin/Mental_Health101")
               )#sidebarMenu      
               ) #dashboardSidebar

#3 ValueBox in the DashBoard Tab   
     frow1 <- fluidRow(
      valueBoxOutput("value1")
      ,valueBoxOutput("value2")
      ,valueBoxOutput("value3")
    )#fluidRow
    

#Tables in the Comments Tab
     
     frow2 <- fluidRow( 
       #Reason for Taking Course
       tags$style(HTML("
                       
                       
                       .box.box-solid.box-primary>.box-header {
                       color:#fff;
                       background:#0277cc
                       }
                       
                       .box.box-solid.box-primary{
                       border-bottom-color:#0277cc;
                       border-left-color:#0277cc;
                       border-right-color:#0277cc;
                       border-top-color:#0277cc;
                       }
                       
                       "))
       ,box(
         title = "Reasons for Taking This Course:"
         ,status = "primary"
         ,solidHeader = TRUE 
         ,collapsible = TRUE 
         ,collapsed = FALSE
         ,dataTableOutput('Reasons'), height = "350px", width="100px"
       ) #box
       ) #fluidRow
     
     #What Users Enjoyed The Most 
     frow3 <- fluidRow(tags$style(HTML("
                                       
                                       
                                       .box.box-solid.box-success>.box-header {
                                       color:#fff;
                                       background:#0277cc
                                       }
                                       
                                       .box.box-solid.box-success{
                                       border-bottom-color:#0277cc;
                                       border-left-color:#0277cc;
                                       border-right-color:#0277cc;
                                       border-top-color:#0277cc;
                                       }
                                       
                                       ")) 
                       
                       ,box(
                         title = "Users Enjoyed:"
                         ,status = "success"
                         ,solidHeader = TRUE 
                         ,collapsible = TRUE 
                         ,collapsed = FALSE
                        ,dataTableOutput('Enjoy'), height = "350px", width="50px"
                         
                       ) #box
     ) #fluidRow
     
    
# combine the fluid row with reactive graph to make the body
body <- dashboardBody( tabItems(
                     tabItem(tabName="dashboard",
                              frow1, 
                      tags$b(h3("User Count")),h4("*Some enrolled users may have enrolled in more than one of the courses"),
                      tags$b(h3("Course Completion")),
                      h4("*Guests Users: means they have viewed some or all of course module/book content"),
                      h4("*Enrolled Users: means they have viewed the course module/book content and the quizzes, therefore recieved a badge generated by the system"),
                     HTML ('</br>'),
                     selectInput("input1", label = h3("Select Measure"),
                                  choices = c(
                        "The information presented was clear"="Clear",
                        "The information presented  was useful"="Useful",
                        "I could find my way around the course easily"="Navigate",
                        "The interactive activities were engaging"="Engaging",
                        "Overall, I was satisfied with the course"="Satisfied"),
                        selected="Satisfied") #selectInput
                     ,plotlyOutput("plot1",width = "100%", height = "350px")
                     )#tabItem
                     
                     ,tabItem(tabName="comments"
                              ,frow2 #Reason for Taking Course
                              ,HTML ('</br>')  
                              ,HTML ('</br>')  
                              ,HTML ('</br>')  
                              ,frow3 #What Users Enjoyed The Most 
                     )#tabItem
                     )#tabItems
                      ) #dashboardBody 


#completing the ui part with dashboardPage
ui <- dashboardPage(title = 'Mental Health 101 Dashboard', header, sidebar, body, skin='blue')